"use client";

import { useState } from "react";

export default function ProposalGenerator({
  clientName,
  clientCompany,
  projects,
}: {
  clientName: string;
  clientCompany: string;
  projects: { id: string; name: string; value_inr: number | null }[];
}) {
  const [scope, setScope] = useState("");
  const [deliverables, setDeliverables] = useState("");
  const [timeline, setTimeline] = useState("");
  const [amount, setAmount] = useState("");
  const [projectId, setProjectId] = useState(projects[0]?.id ?? "");
  const [generated, setGenerated] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    setGenerated("");
    const project = projects.find((p) => p.id === projectId);
    const value = amount || (project?.value_inr != null ? String(project.value_inr) : "");
    setLoading(true);
    try {
      const res = await fetch("/api/ai/proposal", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          clientName,
          clientCompany: clientCompany || undefined,
          projectName: project?.name,
          scope,
          deliverables,
          timeline,
          amountInr: value,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to generate proposal");
      setGenerated(data.text);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-6">
      <form onSubmit={handleGenerate} className="rounded-2xl border border-zinc-800 bg-zinc-900/80 p-6 space-y-4">
        {projects.length > 0 && (
          <label className="block">
            <span className="text-sm font-medium text-zinc-400">Link to project</span>
            <select value={projectId} onChange={(e) => setProjectId(e.target.value)} className="input-dark">
              {projects.map((p) => (
                <option key={p.id} value={p.id}>{p.name} {p.value_inr != null ? `(₹${Number(p.value_inr).toLocaleString("en-IN")})` : ""}</option>
              ))}
            </select>
          </label>
        )}
        <label className="block">
          <span className="text-sm font-medium text-zinc-400">Scope of work</span>
          <textarea value={scope} onChange={(e) => setScope(e.target.value)} rows={3} className="input-dark" placeholder="Brief description of what you'll do" />
        </label>
        <label className="block">
          <span className="text-sm font-medium text-zinc-400">Deliverables</span>
          <textarea value={deliverables} onChange={(e) => setDeliverables(e.target.value)} rows={3} className="input-dark" placeholder="One per line or paragraph" />
        </label>
        <label className="block">
          <span className="text-sm font-medium text-zinc-400">Timeline</span>
          <input type="text" value={timeline} onChange={(e) => setTimeline(e.target.value)} className="input-dark" placeholder="e.g. 4 weeks from kickoff" />
        </label>
        <label className="block">
          <span className="text-sm font-medium text-zinc-400">Amount (₹)</span>
          <input type="number" min={0} value={amount} onChange={(e) => setAmount(e.target.value)} className="input-dark" placeholder={projects[0]?.value_inr != null ? String(projects[0].value_inr) : "50000"} />
        </label>
        <button type="submit" disabled={loading} className="btn-press rounded-xl bg-brand-500 px-5 py-2.5 font-medium text-white hover:bg-brand-400 disabled:opacity-60 disabled:cursor-not-allowed">
          {loading ? "Generating with AI…" : "Generate proposal draft"}
        </button>
      </form>
      {error && (
        <p className="text-sm text-red-400 rounded-xl bg-red-950/30 border border-red-900/50 px-4 py-2">{error}</p>
      )}
      {generated && (
        <div className="rounded-2xl border border-zinc-800 bg-zinc-900/80 p-6">
          <p className="text-sm font-medium text-zinc-400 mb-2">AI-generated draft (Groq) — copy and edit</p>
          <pre className="whitespace-pre-wrap text-sm text-zinc-200 font-sans bg-zinc-800/50 rounded-xl p-4 max-h-96 overflow-auto">
            {generated}
            {"\n\n— Generated by OnboardEasy. Customise and send as PDF when ready."}
          </pre>
          <button
            type="button"
            onClick={() => navigator.clipboard.writeText(generated)}
            className="mt-3 rounded-lg bg-zinc-700 px-4 py-2 text-sm text-zinc-200 hover:bg-zinc-600"
          >
            Copy to clipboard
          </button>
        </div>
      )}
    </div>
  );
}
